arch: 
       - arm64
       - amd64
language: python
python: 
       - 3.7
       -3.5
       -3.6
       - 3.4
       - 2.7
sudo : false
env:
install:
    - pip install -e . coveralls
script:
    - nosetests --with-coverage --cover-package=ipython_genutils ipython_genutils

after_success:
    - coveralls

